#!/bin/bash
# anicenttwo-proj-init Script
# Generated by anicenttwo-proj-init skill
# Usage: bash init-project.sh [project-name] [stack]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
PROJECT_NAME="${1:-my-project}"
STACK="${2:-vite-tanstack}"
PKG_MANAGER="${3:-bun}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ASSETS_REF_DIR="$SCRIPT_DIR/../assets/reference-configs"
ASSETS_HOOKS_DIR="$SCRIPT_DIR/../assets/hooks"
ASSETS_TEMPLATES_DIR="$SCRIPT_DIR/../assets/templates"

echo -e "${BLUE}=== anicenttwo-proj-init ===${NC}"
echo -e "Project: ${GREEN}$PROJECT_NAME${NC}"
echo -e "Stack: ${GREEN}$STACK${NC}"
echo -e "Package Manager: ${GREEN}$PKG_MANAGER${NC}"
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

ensure_runtime_gitignore_block() {
    local file_path="$1"
    local begin_marker="# BEGIN: claude-runtime-temp (managed by anicenttwo-proj-init)"
    local end_marker="# END: claude-runtime-temp"

    local block
    block=$(cat <<'BLOCK_EOF'
# BEGIN: claude-runtime-temp (managed by anicenttwo-proj-init)
.claude/settings.local.json
.claude/.atomic_pending
.claude/.session-id
.claude/.tool-call-count
.claude/.session-handoff.md
.claude/.task-state.json
.claude/.task-handoff.md
.claude/.context-pressure/
.claude/*.tmp
.claude/*.bak
.claude/*.bak.*
.claude/*.backup-*
# END: claude-runtime-temp
BLOCK_EOF
)

    if [ ! -f "$file_path" ]; then
        touch "$file_path"
    fi

    if ! grep -Fq "$begin_marker" "$file_path"; then
        printf "\n%s\n" "$block" >> "$file_path"
        return
    fi

    local tmp_file
    tmp_file="$(mktemp)"
    awk -v begin="$begin_marker" -v end="$end_marker" -v repl="$block" '
      $0 == begin {
        print repl
        skipping = 1
        next
      }
      skipping && $0 == end {
        skipping = 0
        next
      }
      !skipping { print }
    ' "$file_path" > "$tmp_file"
    mv "$tmp_file" "$file_path"
}

ensure_gitignore_entry() {
    local file_path="$1"
    local entry="$2"
    if ! grep -Fxq "$entry" "$file_path"; then
        printf "%s\n" "$entry" >> "$file_path"
    fi
}

write_plan_pointer() {
    local active_plan="${1:-}"
    cat > docs/plan.md << EOF
# Plan Pointer (Compatibility)

Active plans live in \`plans/\`. Create new plans with:
  bash scripts/new-plan.sh --slug my-feature

Current Active Plan: ${active_plan:-\\(none\\)}

---
*Updated: $(date '+%Y-%m-%d %H:%M')*
EOF
}

install_workflow_templates() {
    mkdir -p .claude/templates

    if [ -d "$ASSETS_TEMPLATES_DIR" ] && [ -f "$ASSETS_TEMPLATES_DIR/research.template.md" ]; then
        cp "$ASSETS_TEMPLATES_DIR/research.template.md" .claude/templates/research.template.md
    else
        cat > .claude/templates/research.template.md << 'EOF'
# {{PROJECT_NAME}} — Research Notes

> **Last Updated**: {{DATE}}
> **Scope**: (what area of the codebase was researched)
> **Usage**: Store deep codebase findings and hidden contracts here, not in chat-only summaries.

## Codebase Map
| File | Purpose | Key Exports |
|------|---------|-------------|

## Architecture Observations
### Patterns & Conventions
### Implicit Contracts
### Edge Cases & Intricacies

## Technical Debt / Risks

## Research Conclusions
### What to Preserve
### What to Change
### Open Questions
EOF
    fi

    if [ -d "$ASSETS_TEMPLATES_DIR" ] && [ -f "$ASSETS_TEMPLATES_DIR/plan.template.md" ]; then
        cp "$ASSETS_TEMPLATES_DIR/plan.template.md" .claude/templates/plan.template.md
    else
        cat > .claude/templates/plan.template.md << 'EOF'
# Plan: {{TITLE}}

> **Status**: Draft
> **Created**: {{TIMESTAMP}}
> **Slug**: {{SLUG}}
> **Research**: See `tasks/research.md`

## Approach
### Strategy
### Trade-offs
| Option | Pros | Cons | Decision |
|--------|------|------|----------|

## Detailed Design
### File Changes
| File | Action | Description |
|------|--------|-------------|

### Code Snippets
### Data Flow

## Risk Assessment
| Risk | Likelihood | Impact | Mitigation |
|------|------------|--------|------------|

## Task Contracts
- Contract file: `tasks/contracts/{{SLUG}}.contract.md`
- Template: `.claude/templates/contract.template.md`
- Verification command: `bash scripts/verify-contract.sh --contract tasks/contracts/{{SLUG}}.contract.md --strict`

## Annotations
<!-- [NOTE]: prefixed inline. Claude processes all and revises. -->

## Task Breakdown
- [ ] ...
EOF
    fi

    if [ -d "$ASSETS_TEMPLATES_DIR" ] && [ -f "$ASSETS_TEMPLATES_DIR/contract.template.md" ]; then
        cp "$ASSETS_TEMPLATES_DIR/contract.template.md" .claude/templates/contract.template.md
    else
        cat > .claude/templates/contract.template.md << 'EOF'
# Task Contract: {{TASK_SLUG}}

> **Status**: Pending
> **Plan**: plans/plan-YYYYMMDD-HHMM-{{TASK_SLUG}}.md
> **Owner**: {{OWNER}}
> **Last Updated**: {{TIMESTAMP}}

## Goal

Describe the exact outcome this task must deliver.

## Exit Criteria (Machine Verifiable)

```yaml
exit_criteria:
  files_exist:
    - src/modules/{{TASK_SLUG}}/index.ts
  tests_pass:
    - path: tests/unit/{{TASK_SLUG}}.test.ts
  commands_succeed:
    - bun run typecheck
  files_contain:
    - path: src/modules/{{TASK_SLUG}}/index.ts
      pattern: "export"
```

## Acceptance Notes (Human Review)

- Functional behavior:
- Edge cases:
- Regression risks:

## Optional Visual Checks

- Screenshot path (optional):
- What to verify visually:
EOF
    fi
}

install_workflow_helpers() {
    mkdir -p scripts

    if [ -d "$ASSETS_TEMPLATES_DIR/helpers" ]; then
        cp "$ASSETS_TEMPLATES_DIR/helpers/"*.sh scripts/ 2>/dev/null || true
        chmod +x scripts/new-plan.sh scripts/plan-to-todo.sh scripts/archive-workflow.sh scripts/verify-contract.sh scripts/check-task-sync.sh 2>/dev/null || true
        return
    fi

    cat > scripts/new-plan.sh << 'EOF'
#!/bin/bash
set -euo pipefail
echo "Missing helper template: new-plan.sh"
exit 1
EOF

    cat > scripts/plan-to-todo.sh << 'EOF'
#!/bin/bash
set -euo pipefail
echo "Missing helper template: plan-to-todo.sh"
exit 1
EOF

    cat > scripts/archive-workflow.sh << 'EOF'
#!/bin/bash
set -euo pipefail
echo "Missing helper template: archive-workflow.sh"
exit 1
EOF

    cat > scripts/verify-contract.sh << 'EOF'
#!/bin/bash
set -euo pipefail
echo "Missing helper template: verify-contract.sh"
exit 1
EOF

    cat > scripts/check-task-sync.sh << 'EOF'
#!/bin/bash
set -euo pipefail
echo "Missing helper template: check-task-sync.sh"
exit 1
EOF

    chmod +x scripts/new-plan.sh scripts/plan-to-todo.sh scripts/archive-workflow.sh scripts/verify-contract.sh scripts/check-task-sync.sh
}

ensure_task_sync_package_script() {
    local package_file="package.json"

    if [ ! -f "$package_file" ]; then
        return
    fi

    if command_exists node; then
        node -e '
const fs = require("fs");
const file = process.argv[1];
const pkg = JSON.parse(fs.readFileSync(file, "utf8"));
pkg.private ??= true;
pkg.scripts ??= {};
pkg.scripts["check:task-sync"] = "bash scripts/check-task-sync.sh";
fs.writeFileSync(file, JSON.stringify(pkg, null, 2) + "\n");
' "$package_file"
        return
    fi

    echo -e "${YELLOW}Warning: node not found. Could not inject check:task-sync into package.json.${NC}"
}

# Check package manager
check_package_manager() {
    case $PKG_MANAGER in
        bun)
            if ! command_exists bun; then
                echo -e "${YELLOW}Bun not found. Installing...${NC}"
                curl -fsSL https://bun.sh/install | bash
            fi
            ;;
        pnpm)
            if ! command_exists pnpm; then
                echo -e "${YELLOW}pnpm not found. Installing...${NC}"
                npm install -g pnpm
            fi
            ;;
        npm)
            # npm comes with Node.js
            ;;
    esac
}

# Create project based on stack
create_project() {
    case $STACK in
        vite-tanstack)
            echo -e "${BLUE}Creating Vite + TanStack Router project...${NC}"
            if [ "$PKG_MANAGER" = "bun" ]; then
                bun create vite "$PROJECT_NAME" -- --template react-ts
            else
                $PKG_MANAGER create vite@latest "$PROJECT_NAME" -- --template react-ts
            fi
            cd "$PROJECT_NAME"

            # Install TanStack Router
            $PKG_MANAGER add @tanstack/react-router
            $PKG_MANAGER add -D @tanstack/router-devtools @tanstack/router-plugin

            # Install TanStack Query
            $PKG_MANAGER add @tanstack/react-query
            $PKG_MANAGER add -D @tanstack/react-query-devtools

            # Install shadcn/ui
            npx shadcn@latest init -y
            npx shadcn@latest add button input table form dialog select card tabs

            # Install additional deps
            $PKG_MANAGER add @supabase/supabase-js zustand
            $PKG_MANAGER add react-hook-form @hookform/resolvers zod
            $PKG_MANAGER add clsx tailwind-merge lucide-react date-fns
            ;;

        remix)
            echo -e "${BLUE}Creating Remix project...${NC}"
            npx create-remix@latest "$PROJECT_NAME" --yes
            cd "$PROJECT_NAME"

            # Install shadcn/ui
            npx shadcn@latest init -y
            npx shadcn@latest add button input table form dialog select card tabs

            # Install additional deps
            $PKG_MANAGER add @supabase/supabase-js @supabase/ssr zustand
            $PKG_MANAGER add react-hook-form @hookform/resolvers zod
            $PKG_MANAGER add clsx tailwind-merge class-variance-authority
            $PKG_MANAGER add lucide-react date-fns nanoid
            ;;

        umi-antd-pro)
            echo -e "${BLUE}Creating UmiJS + Ant Design Pro project...${NC}"
            npm create umi -- "$PROJECT_NAME"
            cd "$PROJECT_NAME"

            $PKG_MANAGER add @supabase/supabase-js
            $PKG_MANAGER add date-fns lodash-es
            $PKG_MANAGER add -D @types/lodash-es
            ;;

        expo-nativewind)
            echo -e "${BLUE}Creating Expo + NativeWind project...${NC}"
            npx create-expo-app "$PROJECT_NAME" -t expo-template-blank-typescript
            cd "$PROJECT_NAME"

            $PKG_MANAGER add nativewind
            $PKG_MANAGER add -D tailwindcss
            npx tailwindcss init

            $PKG_MANAGER add @tanstack/react-query @supabase/supabase-js zustand
            ;;

        monorepo)
            echo -e "${BLUE}Creating Bun + Turborepo monorepo...${NC}"
            bunx create-turbo@latest "$PROJECT_NAME"
            cd "$PROJECT_NAME"
            ;;

        *)
            echo -e "${RED}Unknown stack: $STACK${NC}"
            exit 1
            ;;
    esac
}

# Create project structure
create_structure() {
    echo -e "${BLUE}Creating project structure...${NC}"
    local TODAY
    local NOW
    TODAY="$(date +%Y-%m-%d)"
    NOW="$(date '+%Y-%m-%d %H:%M')"

    mkdir -p docs/architecture
    mkdir -p docs/reference-configs
    mkdir -p tasks/archive
    mkdir -p tasks/contracts
    mkdir -p plans/archive
    mkdir -p .claude/hooks
    mkdir -p .claude/templates
    mkdir -p .ops
    mkdir -p artifacts

    # Create documentation files
    cat > docs/PROGRESS.md << EOF
# Project Milestones

> Use this file for milestone checkpoints only.
> Active execution belongs in \`tasks/todo.md\`, \`tasks/lessons.md\`, and \`tasks/research.md\`.

## Milestones

- [x] Repository scaffolded
- [ ] First feature milestone shipped

## Notes

- Record releases, migrations, and major checkpoints here.

---
*Last updated: ${TODAY}*
EOF

    cat > docs/CHANGELOG.md << 'EOF'
# Changelog

All notable changes to this project will be documented in this file.

## [Unreleased]

### Added
- Initial project setup

---
*Format based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)*
EOF

    cat > tasks/todo.md << EOF
# Task Execution Checklist (Primary)

> Update this file for every non-chat task that changes the repo.
> Keep verification evidence and follow-up notes here.

## Plan
- [ ] Define scope and acceptance criteria
- [ ] Break down into checkable tasks

## Execution
- [ ] Implement task 1
- [ ] Implement task 2

## Review Section
- Verification evidence:
- Behavior diff notes:
- Risks / follow-ups:

---
*Updated: ${TODAY}*
EOF

    cat > tasks/lessons.md << EOF
# Lessons Learned (Self-Improvement Loop)

> Capture correction-derived prevention rules here.
> Promote repeated patterns into durable project rules during spa day.

## Template
- Date:
- Triggered by correction:
- Mistake pattern:
- Prevention rule:
- Where to apply next time:

---
*Updated: ${TODAY}*
EOF

    install_workflow_templates

    if [ -f ".claude/templates/research.template.md" ]; then
        sed \
          -e "s/{{PROJECT_NAME}}/${PROJECT_NAME}/g" \
          -e "s/{{DATE}}/${NOW}/g" \
          .claude/templates/research.template.md > tasks/research.md
    else
        cat > tasks/research.md << EOF
# ${PROJECT_NAME} — Research Notes

> **Last Updated**: ${NOW}
> **Scope**: (what area of the codebase was researched)
> **Usage**: Store deep codebase findings and hidden contracts here, not in chat-only summaries.

## Codebase Map
| File | Purpose | Key Exports |
|------|---------|-------------|

## Architecture Observations
### Patterns & Conventions
### Implicit Contracts
### Edge Cases & Intricacies

## Technical Debt / Risks

## Research Conclusions
### What to Preserve
### What to Change
### Open Questions
EOF
    fi

    write_plan_pointer ""
    install_workflow_helpers
    ensure_task_sync_package_script

    cat > .claude/settings.json << 'EOF'
{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Edit|Write",
        "hooks": [
          { "type": "command", "command": "bash .claude/hooks/worktree-guard.sh" },
          { "type": "command", "command": "bash .claude/hooks/tdd-guard-hook.sh" },
          { "type": "command", "command": "bash .claude/hooks/pre-code-change.sh" }
        ]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Edit|Write",
        "hooks": [
          { "type": "command", "command": "bash .claude/hooks/anti-simplification.sh" },
          { "type": "command", "command": "bash .claude/hooks/doc-drift-guard.sh" },
          { "type": "command", "command": "bash .claude/hooks/task-handoff.sh" },
          { "type": "command", "command": "bash .claude/hooks/atomic-pending.sh" }
        ]
      },
      {
        "matcher": "Bash",
        "hooks": [
          { "type": "command", "command": "bash .claude/hooks/post-bash.sh" },
          { "type": "command", "command": "bash .claude/hooks/atomic-commit.sh" },
          { "type": "command", "command": "bash .claude/hooks/changelog-guard.sh" }
        ]
      },
      {
        "matcher": ".*",
        "hooks": [{ "type": "command", "command": "bash .claude/hooks/context-pressure-hook.sh" }]
      }
    ],
    "UserPromptSubmit": [
      {
        "hooks": [{ "type": "command", "command": "bash .claude/hooks/prompt-guard.sh" }]
      }
    ]
  }
}
EOF

    # Copy hook scripts into the project
    if [ -d "$ASSETS_HOOKS_DIR" ]; then
        cp "$ASSETS_HOOKS_DIR"/*.sh .claude/hooks/ 2>/dev/null || true
        chmod +x .claude/hooks/*.sh 2>/dev/null || true
        echo -e "${GREEN}Hooks installed to .claude/hooks/${NC}"
    else
        echo -e "${YELLOW}Warning: Hook scripts not found at $ASSETS_HOOKS_DIR${NC}"
        echo -e "${YELLOW}  .claude/settings.json references hooks that don't exist yet.${NC}"
        echo -e "${YELLOW}  Add hook scripts to .claude/hooks/ or remove references from settings.json.${NC}"
    fi

    if [ -d "$ASSETS_REF_DIR" ]; then
        cp "$ASSETS_REF_DIR"/*.md docs/reference-configs/
    else
        cat > docs/reference-configs/changelog-versioning.md << 'EOF'
# Changelog & Versioning Reference

Use this file for detailed release-note and semantic-versioning rules.
EOF

        cat > docs/reference-configs/git-strategy.md << 'EOF'
# Git Strategy Reference

Use this file for branch model and commit convention details.
EOF

        cat > docs/reference-configs/release-deploy.md << 'EOF'
# Release & Deployment Reference

Use this file for release pipeline and deployment trigger details.
EOF

        cat > docs/reference-configs/ai-workflows.md << 'EOF'
# AI Workflows Reference

Use this file for extended AI workflow templates, tasks-first session handoff, and milestone-only progress guidance.
EOF

        cat > docs/reference-configs/coding-standards.md << 'EOF'
# Coding Standards Reference

Use this file for detailed coding constraints and refactor thresholds.
EOF

        cat > docs/reference-configs/development-protocol.md << 'EOF'
# Development Protocol Reference

Use this file for detailed feature/bug flow playbooks, repo-local task sync rules, and final response requirements.
EOF

        cat > docs/reference-configs/workflow-orchestration.md << 'EOF'
# Workflow Orchestration Reference

Use this file for advanced plan/execution orchestration patterns.
EOF

        cat > docs/reference-configs/spa-day-protocol.md << 'EOF'
# Spa Day Protocol

Periodic cleanup protocol to reduce context bloat and rule conflicts.

## 1. Rule Consolidation
- Merge overlapping rules in `docs/reference-configs/`.
- Remove contradictory instructions and keep one canonical rule per topic.

## 2. CLAUDE/AGENTS Routing Freshness
- Verify all routed paths still exist.
- Remove stale references from CLAUDE.md/AGENTS.md indexes.

## 3. Lessons Graduation
- Promote repeated lessons from `tasks/lessons.md` into durable rules.
- Archive one-off or obsolete lessons.

## 4. Research Pruning
- Remove already-implemented investigation items from `tasks/research.md`.
- Keep only unresolved findings and open questions.

## 5. Docs Reality Check
- Sync `docs/architecture.md` and `docs/tech-stack.md` with current codebase.
- Flag drift for immediate correction.

## 6. Contract Hygiene
- Move fulfilled contracts from `tasks/contracts/` into an archive folder if needed.
- Keep active contracts only for in-flight tasks.
EOF
    fi

    # Update .gitignore with explicit entries only
    touch .gitignore
    ensure_gitignore_entry .gitignore "# Project-specific"
    ensure_gitignore_entry .gitignore "artifacts/"
    ensure_gitignore_entry .gitignore "coverage/"
    ensure_gitignore_entry .gitignore "*.tar.gz"
    ensure_gitignore_entry .gitignore "*.tgz"
    ensure_gitignore_entry .gitignore ""
    ensure_gitignore_entry .gitignore "# Environment"
    ensure_gitignore_entry .gitignore ".env"
    ensure_gitignore_entry .gitignore ".env.*"
    ensure_gitignore_entry .gitignore "!.env.example"
    ensure_gitignore_entry .gitignore ""
    ensure_gitignore_entry .gitignore "# OS metadata"
    ensure_gitignore_entry .gitignore ".DS_Store"
    ensure_runtime_gitignore_block .gitignore

    # Create .env.example
    cat > .env.example << 'EOF'
# Supabase
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-anon-key

# Optional: Service Role (server-side only)
# SUPABASE_SERVICE_ROLE_KEY=your-service-role-key

# App Config
NODE_ENV=development
PORT=3000
EOF

    echo -e "${GREEN}Project structure created!${NC}"
}

# Install dev tools
install_dev_tools() {
    echo -e "${BLUE}Installing dev tools...${NC}"

    # Biome (Linting & Formatting)
    $PKG_MANAGER add -D @biomejs/biome

    # Testing
    $PKG_MANAGER add -D vitest @testing-library/react @testing-library/jest-dom

    # Initialize Biome
    npx @biomejs/biome init

    echo -e "${GREEN}Dev tools installed!${NC}"
}

# Write version stamp into the generated project
write_version_stamp() {
    local skill_version_file="$SCRIPT_DIR/../assets/skill-version.json"
    local stamp_dir=".claude"
    local stamp_file="$stamp_dir/.skill-version"
    local sv_version="unknown"
    local sv_template_version="unknown"

    if [ -f "$skill_version_file" ] && command_exists bun; then
        sv_version=$(bun -e "console.log(JSON.parse(require('fs').readFileSync('$skill_version_file','utf-8')).version)")
        sv_template_version=$(bun -e "console.log(JSON.parse(require('fs').readFileSync('$skill_version_file','utf-8')).templateVersion)")
    elif [ -f "$skill_version_file" ] && command_exists node; then
        sv_version=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$skill_version_file','utf-8')).version)")
        sv_template_version=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$skill_version_file','utf-8')).templateVersion)")
    fi

    mkdir -p "$stamp_dir"
    cat > "$stamp_file" << STAMP_EOF
skill_version=$sv_version
template_version=$sv_template_version
generated_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
plan_type=${STACK}
STAMP_EOF
    echo -e "${GREEN}Version stamp written to $stamp_file${NC}"
}

# Run a skill lifecycle hook (if bun is available)
run_skill_hook() {
    local event="$1"
    local hook_script="$SCRIPT_DIR/run-skill-hook.ts"

    if command_exists bun && [ -f "$hook_script" ]; then
        bun "$hook_script" "$event" --context "{\"projectName\":\"$PROJECT_NAME\",\"stack\":\"$STACK\"}" 2>&1 || {
            if [[ "$event" == pre-* ]]; then
                echo -e "${RED}Pre-hook $event failed, aborting.${NC}"
                return 1
            else
                echo -e "${YELLOW}Post-hook $event warning (non-fatal).${NC}"
            fi
        }
    fi
}

# Main execution
main() {
    run_skill_hook "pre-init" || exit 1

    check_package_manager
    create_project
    create_structure
    install_dev_tools
    write_version_stamp

    run_skill_hook "post-init"

    echo ""
    echo -e "${GREEN}=== Project initialized successfully! ===${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. cd $PROJECT_NAME"
    echo "  2. Copy .env.example to .env and configure"
    echo "  3. Run: $PKG_MANAGER run dev"
    echo "  4. Run: bash scripts/new-plan.sh --slug first-feature"
    echo "  5. Capture research in tasks/research.md and iterate plan annotations"
    echo ""
}

main
