#!/usr/bin/env bash
# setup-hooks.sh — Install Claude Code hooks for a project generated by full-project-skill.
# Note: These hooks depend on Claude Code's hook event system and JSON protocol.
# They are not compatible with Codex CLI hooks.
#
# Usage:
#   ./scripts/setup-hooks.sh [--pm <package-manager>] [--project-dir <path>] [--dry-run] [--backup] [--replace]
#
# Actions:
# 1) Read assets/hooks/settings.template.json
# 2) Strip metadata keys and substitute {{PM}}
# 3) Write/merge hooks into <project-dir>/.claude/settings.json
# 4) Copy assets/hooks/*.sh into <project-dir>/.claude/hooks and chmod +x

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATE="$SKILL_ROOT/assets/hooks/settings.template.json"
HOOK_ASSETS_DIR="$SKILL_ROOT/assets/hooks"

# Defaults
PM="bun"
PROJECT_DIR="$(pwd)"
DRY_RUN=false
BACKUP=false
REPLACE=false

pick_runtime() {
  if command -v bun >/dev/null 2>&1; then
    echo "bun"
  else
    echo "node"
  fi
}

generate_hooks_json() {
  local runtime
  runtime="$(pick_runtime)"

  "$runtime" -e "
    const fs = require('fs');
    const template = JSON.parse(fs.readFileSync('$TEMPLATE', 'utf8'));
    const hooks = template.hooks;

    function clean(obj) {
      if (Array.isArray(obj)) return obj.map(clean);
      if (obj && typeof obj === 'object') {
        const result = {};
        for (const [k, v] of Object.entries(obj)) {
          if (k.startsWith('$')) continue;
          result[k] = clean(v);
        }
        return result;
      }
      return obj;
    }

    const cleaned = clean(hooks);
    const json = JSON.stringify(cleaned, null, 2);
    const substituted = json.replace(/\\{\\{PM\\}\\}/g, '$PM');
    console.log(substituted);
  "
}

install_hook_scripts() {
  local hooks_dir="$1"
  local copied_count=0

  mkdir -p "$hooks_dir"

  for src in "$HOOK_ASSETS_DIR"/*.sh; do
    [[ -f "$src" ]] || continue
    local file_name
    file_name="$(basename "$src")"
    cp "$src" "$hooks_dir/$file_name"
    chmod +x "$hooks_dir/$file_name" 2>/dev/null || true
    copied_count=$((copied_count + 1))
  done

  echo "$copied_count"
}

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --pm) PM="$2"; shift 2 ;;
    --project-dir) PROJECT_DIR="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --backup) BACKUP=true; shift ;;
    --replace) REPLACE=true; shift ;;
    -h|--help)
      echo "Usage: setup-hooks.sh [--pm <package-manager>] [--project-dir <path>] [--dry-run] [--backup] [--replace]"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

if [[ ! -f "$TEMPLATE" ]]; then
  echo "Error: Template not found at $TEMPLATE"
  exit 1
fi

if [[ ! -d "$HOOK_ASSETS_DIR" ]]; then
  echo "Error: Hook assets directory not found at $HOOK_ASSETS_DIR"
  exit 1
fi

HOOKS_JSON="$(generate_hooks_json)"
SETTINGS_DIR="$PROJECT_DIR/.claude"
SETTINGS_FILE="$SETTINGS_DIR/settings.json"
HOOKS_DIR="$SETTINGS_DIR/hooks"

if [[ "$DRY_RUN" == true ]]; then
  echo "Generated hooks configuration (dry run):"
  echo "$HOOKS_JSON"
  echo ""
  echo "Hook scripts to install:"
  ls -1 "$HOOK_ASSETS_DIR"/*.sh 2>/dev/null | sed "s|$HOOK_ASSETS_DIR/|  - |" || true
  exit 0
fi

mkdir -p "$SETTINGS_DIR"

if [[ -f "$SETTINGS_FILE" ]]; then
  if [[ "$BACKUP" == true ]]; then
    cp "$SETTINGS_FILE" "$SETTINGS_FILE.bak"
    echo "Backup created: $SETTINGS_FILE.bak"
  fi
  local_runtime="$(pick_runtime)"
  if [[ "$REPLACE" == true ]]; then
    "$local_runtime" -e "
      const fs = require('fs');
      const existing = JSON.parse(fs.readFileSync('$SETTINGS_FILE', 'utf8'));
      const hooks = JSON.parse(process.argv[1]);
      existing.hooks = hooks;
      fs.writeFileSync('$SETTINGS_FILE', JSON.stringify(existing, null, 2) + '\n');
      console.log('Replaced hooks in existing $SETTINGS_FILE');
    " "$HOOKS_JSON"
  else
    "$local_runtime" -e "
      const fs = require('fs');
      const existing = JSON.parse(fs.readFileSync('$SETTINGS_FILE', 'utf8'));
      const hooks = JSON.parse(process.argv[1]);
      existing.hooks = { ...existing.hooks, ...hooks };
      fs.writeFileSync('$SETTINGS_FILE', JSON.stringify(existing, null, 2) + '\n');
      console.log('Merged hooks into existing $SETTINGS_FILE');
    " "$HOOKS_JSON"
  fi
else
  if command -v python3 >/dev/null 2>&1; then
    echo "{\"hooks\": $HOOKS_JSON}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
print(json.dumps(data, indent=2))
" > "$SETTINGS_FILE"
  else
    echo "{\"hooks\": $HOOKS_JSON}" > "$SETTINGS_FILE"
  fi
  echo "Created $SETTINGS_FILE with hooks"
fi

COPIED_COUNT="$(install_hook_scripts "$HOOKS_DIR")"

echo ""
echo "Hooks installed successfully!"
echo "  - settings: $SETTINGS_FILE"
echo "  - scripts:  $HOOKS_DIR ($COPIED_COUNT files)"
echo ""
echo "To verify:"
echo "  cat $SETTINGS_FILE"
echo "  ls -la $HOOKS_DIR"
