#!/usr/bin/env bash
# setup-hooks.sh — Install hooks for a project generated by split project skills.
# Supports Claude Code and Codex CLI platforms.
#
# Usage:
#   ./scripts/setup-hooks.sh [--pm <package-manager>] [--project-dir <path>] [--platform <claude|codex|both>] [--dry-run] [--backup] [--replace]
#
# Actions:
# 1) Read the appropriate settings template for the target platform(s)
# 2) Strip metadata keys and substitute {{PM}}
# 3) Write/merge hooks into <project-dir>/.<platform>/settings.json
# 4) Copy assets/hooks/*.sh into <project-dir>/.<platform>/hooks and chmod +x

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOK_ASSETS_DIR="$SKILL_ROOT/assets/hooks"

# Defaults
PM="bun"
PROJECT_DIR="$(pwd)"
PLATFORM="both"
DRY_RUN=false
BACKUP=false
REPLACE=false

pick_runtime() {
  if command -v bun >/dev/null 2>&1; then
    echo "bun"
  else
    echo "node"
  fi
}

resolve_template() {
  local platform="$1"
  case "$platform" in
    claude) echo "$HOOK_ASSETS_DIR/settings.template.json" ;;
    codex)  echo "$HOOK_ASSETS_DIR/settings.template.codex.json" ;;
    *)
      echo "Error: Unknown platform '$platform'. Supported: claude, codex, both" >&2
      exit 1
      ;;
  esac
}

resolve_config_dir() {
  local platform="$1"
  local project="$2"
  case "$platform" in
    claude) echo "$project/.claude" ;;
    codex)  echo "$project/.codex" ;;
    *) echo "$project/.$platform" ;;
  esac
}

generate_hooks_json() {
  local template="$1"
  local runtime
  runtime="$(pick_runtime)"

  "$runtime" -e "
    const fs = require('fs');
    const template = JSON.parse(fs.readFileSync('$template', 'utf8'));
    const hooks = template.hooks;

    function clean(obj) {
      if (Array.isArray(obj)) return obj.map(clean);
      if (obj && typeof obj === 'object') {
        const result = {};
        for (const [k, v] of Object.entries(obj)) {
          if (k.startsWith('\$')) continue;
          result[k] = clean(v);
        }
        return result;
      }
      return obj;
    }

    const cleaned = clean(hooks);
    const json = JSON.stringify(cleaned, null, 2);
    const substituted = json.replace(/\\{\\{PM\\}\\}/g, '$PM');
    console.log(substituted);
  "
}

install_hook_scripts() {
  local hooks_dir="$1"
  local copied_count=0

  mkdir -p "$hooks_dir"

  for src in "$HOOK_ASSETS_DIR"/*.sh; do
    [[ -f "$src" ]] || continue
    local file_name
    file_name="$(basename "$src")"
    local content
    content="$(cat "$src")"
    # Substitute {{PM}} in script content
    content="${content//\{\{PM\}\}/$PM}"
    printf '%s\n' "$content" > "$hooks_dir/$file_name"
    chmod +x "$hooks_dir/$file_name" 2>/dev/null || true
    copied_count=$((copied_count + 1))
  done

  echo "$copied_count"
}

resolve_platforms() {
  local platform="$1"
  case "$platform" in
    claude|codex) echo "$platform" ;;
    both) echo "claude codex" ;;
    *)
      echo "Error: Unknown platform '$platform'. Supported: claude, codex, both" >&2
      exit 1
      ;;
  esac
}

install_for_platform() {
  local platform="$1"
  local template config_dir settings_file hooks_dir hooks_json local_runtime copied_count

  template="$(resolve_template "$platform")"
  if [[ ! -f "$template" ]]; then
    echo "Error: Template not found at $template"
    exit 1
  fi

  hooks_json="$(generate_hooks_json "$template")"
  config_dir="$(resolve_config_dir "$platform" "$PROJECT_DIR")"
  settings_file="$config_dir/settings.json"
  hooks_dir="$config_dir/hooks"

  if [[ "$DRY_RUN" == true ]]; then
    echo "Platform: $platform"
    echo "Generated hooks configuration (dry run):"
    echo "$hooks_json"
    echo ""
    echo "Hook scripts to install:"
    ls -1 "$HOOK_ASSETS_DIR"/*.sh 2>/dev/null | sed "s|$HOOK_ASSETS_DIR/|  - |" || true
    echo ""
    return
  fi

  mkdir -p "$config_dir"

  if [[ -f "$settings_file" ]]; then
    if [[ "$BACKUP" == true ]]; then
      cp "$settings_file" "$settings_file.bak"
      echo "Backup created: $settings_file.bak"
    fi

    local_runtime="$(pick_runtime)"
    if [[ "$REPLACE" == true ]]; then
      "$local_runtime" -e "
        const fs = require('fs');
        const existing = JSON.parse(fs.readFileSync('$settings_file', 'utf8'));
        const hooks = JSON.parse(process.argv[1]);
        existing.hooks = hooks;
        fs.writeFileSync('$settings_file', JSON.stringify(existing, null, 2) + '\n');
        console.log('Replaced hooks in existing $settings_file');
      " "$hooks_json"
    else
      "$local_runtime" -e "
        const fs = require('fs');
        const existing = JSON.parse(fs.readFileSync('$settings_file', 'utf8'));
        const hooks = JSON.parse(process.argv[1]);

        const stableStringify = (value) => {
          if (Array.isArray(value)) {
            return '[' + value.map(stableStringify).join(',') + ']';
          }
          if (value && typeof value === 'object') {
            const entries = Object.keys(value)
              .sort()
              .map((key) => JSON.stringify(key) + ':' + stableStringify(value[key]));
            return '{' + entries.join(',') + '}';
          }
          return JSON.stringify(value);
        };

        const mergeDeep = (current, incoming) => {
          if (Array.isArray(current) && Array.isArray(incoming)) {
            const seen = new Set(current.map((item) => stableStringify(item)));
            const merged = [...current];
            for (const item of incoming) {
              const key = stableStringify(item);
              if (!seen.has(key)) {
                merged.push(item);
                seen.add(key);
              }
            }
            return merged;
          }

          if (
            current &&
            incoming &&
            typeof current === 'object' &&
            typeof incoming === 'object' &&
            !Array.isArray(current) &&
            !Array.isArray(incoming)
          ) {
            const result = { ...current };
            for (const [key, value] of Object.entries(incoming)) {
              if (key in result) {
                result[key] = mergeDeep(result[key], value);
              } else {
                result[key] = value;
              }
            }
            return result;
          }

          return incoming;
        };

        const currentHooks =
          existing && typeof existing.hooks === 'object' && existing.hooks !== null
            ? existing.hooks
            : {};
        existing.hooks = mergeDeep(currentHooks, hooks);
        fs.writeFileSync('$settings_file', JSON.stringify(existing, null, 2) + '\n');
        console.log('Merged hooks into existing $settings_file');
      " "$hooks_json"
    fi
  else
    if command -v python3 >/dev/null 2>&1; then
      echo "{\"hooks\": $hooks_json}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
print(json.dumps(data, indent=2))
" > "$settings_file"
    else
      echo "{\"hooks\": $hooks_json}" > "$settings_file"
    fi
    echo "Created $settings_file with hooks"
  fi

  copied_count="$(install_hook_scripts "$hooks_dir")"

  echo ""
  echo "Hooks installed successfully! (platform: $platform)"
  echo "  - settings: $settings_file"
  echo "  - scripts:  $hooks_dir ($copied_count files)"
  echo ""
  echo "To verify:"
  echo "  cat $settings_file"
  echo "  ls -la $hooks_dir"
  echo ""
}

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --pm) PM="$2"; shift 2 ;;
    --project-dir) PROJECT_DIR="$2"; shift 2 ;;
    --platform) PLATFORM="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --backup) BACKUP=true; shift ;;
    --replace) REPLACE=true; shift ;;
    -h|--help)
      echo "Usage: setup-hooks.sh [--pm <package-manager>] [--project-dir <path>] [--platform <claude|codex|both>] [--dry-run] [--backup] [--replace]"
      echo ""
      echo "Platforms:"
      echo "  both    — Install for Claude Code and Codex CLI (default)"
      echo "  claude  — Claude Code only"
      echo "  codex   — Codex CLI"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

if [[ ! -d "$HOOK_ASSETS_DIR" ]]; then
  echo "Error: Hook assets directory not found at $HOOK_ASSETS_DIR"
  exit 1
fi

read -r -a PLATFORMS <<< "$(resolve_platforms "$PLATFORM")"
for platform in "${PLATFORMS[@]}"; do
  install_for_platform "$platform"
done
